server:
  port: 8090

zuul:
  routes:
    data:
      path: /api/**
      sensitiveHeaders: Cookie
      serviceId: data
    auth:
      path: /auth/**
      serviceId: auth 
      
data:
  ribbon:
      listOfServers: http://localhost:9090/
      
auth:
  ribbon:
      listOfServers: http://localhost:8080/

ribbon:
  eureka:
   enabled: false

management:
  security:
    enabled: false

security:
  basic:
    enabled: false
    
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 300000
    
smpath:
  not:
    applicable: /auth/oauth/token,/auth/oauth/check_token


       